# Site settings
title: Spencer Elliott
email: me@elliottsj.com
description: "Spencer Elliott: CS Student, Developer"
baseurl: ""
twitter_username: spe_
github_username:  elliottsj

# Build settings
markdown: redcarpet
permalink: pretty

# redcarpet settings
redcarpet:
  extensions: [footnotes]

# Sass
sass:
  sass_dir: css
  style: :compressed
