# Site settings
title: Spencer Elliott
email: me@elliottsj.com
description: "Spencer Elliott: CS Student, Developer"
baseurl: ""
twitter_username: spe_
github_username:  elliottsj

# Build settings
markdown: kramdown
permalink: pretty

# kramdown settings
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
